<x-layout title="{{ __('Editorial desk') }}">
<div class="page-shell account-page admin-page">
    <header class="page-heading"><div><h1>{{ __('The editorial desk.') }}</h1><p class="muted">{{ __('Keep the conversation thoughtful and the community healthy.') }}</p></div><a href="/dashboard" class="btn btn-outline">{{ __('Your writing desk →') }}</a></header>
    <div class="admin-overview"><span><strong>{{ number_format($stats['users']) }}</strong> {{ __('registered readers') }}</span><span><strong>{{ number_format($stats['posts']) }}</strong> {{ __('published stories') }}</span><span><strong>{{ number_format($stats['reports']) }}</strong> {{ __('open reports') }}</span></div>
    <nav class="admin-nav" aria-label="{{ __('Administration sections') }}"><a href="#reports">{{ __('Reports') }}</a><a href="#moderation">{{ __('Comments') }}</a><a href="#stories">{{ __('Stories') }}</a><a href="#topics">{{ __('Topics') }}</a>@if($canManageUsers)<a href="#people">{{ __('People') }}</a><a href="#audit">{{ __('Audit log') }}</a><a href="/payouts">{{ __('Payouts') }}</a><a href="/admin/settings">{{ __('Site settings') }}</a>@endif</nav>
    <section id="reports" class="admin-section"><div class="section-heading"><h2>{{ __('Reports to review') }}</h2><span class="muted">{{ trans_choice('ui.open_report_count', $stats['reports']) }}</span></div>
        @forelse($reports as $report)<article class="moderation-item"><div><span class="account-status">{{ class_basename($report->reportable_type) }}</span><h3>{{ $report->reportable?->title ?? Str::limit(strip_tags($report->reportable?->body ?? __('Content no longer available')), 110) }}</h3><p>{{ $report->reason }}</p><p class="muted">{{ __('Reported by :name', ['name' => $report->user?->name ?? __('Deleted account')]) }} · {{ $report->created_at->diffForHumans() }}</p></div><form method="post" action="{{ route('admin.reports.update', $report) }}" class="moderation-actions">@csrf @method('PATCH')<button class="btn btn-outline" name="action" value="dismiss">{{ __('Dismiss') }}</button><button class="btn btn-outline" name="action" value="resolve">{{ __('Resolve') }}</button><button class="btn btn-primary" name="action" value="hide">{{ __('Hide content') }}</button></form></article>@empty<div class="admin-empty"><x-icon name="check" /><h3>{{ __('You’re all caught up.') }}</h3><p class="muted">{{ __('New content reports will appear here for review.') }}</p></div>@endforelse
        {{ $reports->withQueryString()->fragment('reports')->links() }}
    </section>
    <section id="moderation" class="admin-section"><h2>{{ __('Comments needing a second look') }}</h2>@forelse($flaggedComments as $comment)<article class="moderation-item"><div><h3>{{ $comment->user?->name ?? __('Deleted account') }}</h3><p>{{ $comment->body }}</p><p class="muted">{{ __('On “:title”', ['title' => $comment->post?->title]) }}</p></div><form method="post" action="{{ route('admin.comments.update', $comment) }}" class="moderation-actions">@csrf @method('PATCH')<button class="btn btn-outline" name="status" value="visible">{{ __('Approve') }}</button><button class="btn btn-outline" name="status" value="hidden">{{ __('Hide comment') }}</button></form></article>@empty<p class="muted">{{ __('No flagged comments. The conversation is in good hands.') }}</p>@endforelse</section>
    <section id="stories" class="admin-section"><h2>{{ __('Published stories') }}</h2><div class="admin-table-wrap" role="region" tabindex="0" aria-label="{{ __('Published stories') }}"><table class="admin-table"><thead><tr><th scope="col">{{ __('Story') }}</th><th scope="col">{{ __('Writer') }}</th><th scope="col">{{ __('Published') }}</th><th scope="col"><span class="sr-only">{{ __('Actions') }}</span></th></tr></thead><tbody>@forelse($posts as $post)<tr><td><a href="{{ url('/@'.$post->author->username.'/'.$post->slug) }}">{{ $post->title }}</a></td><td>{{ $post->author->name }}</td><td>{{ $post->published_at?->format('M j, Y') }}</td><td><form method="post" action="{{ route('admin.posts.update', $post) }}">@csrf @method('PATCH')<button class="text-button" type="submit" aria-label="{{ __('Unpublish :title', ['title' => $post->title]) }}">{{ __('Unpublish') }}</button></form></td></tr>@empty<tr><td colspan="4">{{ __('No stories published yet.') }}</td></tr>@endforelse</tbody></table></div>{{ $posts->withQueryString()->fragment('stories')->links() }}</section>
    <section id="topics" class="admin-section"><h2>{{ __('Categories and tags') }}</h2><div class="taxonomy-grid">@foreach(['categories' => $categories, 'tags' => $tags] as $type => $entries)<div><h3>{{ $type === 'categories' ? __('Categories') : __('Tags') }}</h3><div class="taxonomy-labels">@foreach($entries as $entry)<span>{{ $entry->name }}</span>@endforeach</div><form method="post" action="{{ route('admin.taxonomy.store', $type) }}" class="inline-form">@csrf<label class="field">{{ $type === 'categories' ? __('New category') : __('New tag') }}<input class="form-input" name="name" maxlength="60" required></label><button class="btn btn-outline" type="submit">{{ __('Add') }}</button></form></div>@endforeach</div></section>
    @if($canManageUsers)<section id="people" class="admin-section"><div class="section-heading"><h2>{{ __('The people of Folkscript') }}</h2><form method="get" action="{{ route('admin') }}#people" class="admin-search"><label class="sr-only" for="people-search">{{ __('Find a reader by name or email') }}</label><input id="people-search" class="form-input" name="q" value="{{ request('q') }}" placeholder="{{ __('Find a name or email') }}"><button class="btn btn-outline" type="submit">{{ __('Search') }}</button></form></div>@if(request('q'))<p class="admin-search-reset"><a class="text-button" href="{{ route('admin') }}#people">{{ __('Clear reader search') }}</a></p>@endif
        <div class="admin-table-wrap" role="region" tabindex="0" aria-label="{{ __('Reader access') }}"><table class="admin-table"><thead><tr><th scope="col">{{ __('Reader') }}</th><th scope="col">{{ __('Status') }}</th><th scope="col">{{ __('Access') }}</th></tr></thead><tbody>@forelse($users as $person)<tr><td><strong>{{ $person->name }}</strong><span class="muted table-secondary">{{ $person->email }}</span></td><td><span class="account-status">{{ $person->suspended_at ? __('Suspended') : ($person->hasVerifiedEmail() ? __('Verified') : __('Unverified')) }}</span></td><td>@if($person->id !== auth()->id() && ! $person->hasRole('super-admin') && (auth()->user()->hasRole('super-admin') || ! $person->hasRole('admin')))<form method="post" action="{{ route('admin.users.update', $person) }}" class="user-access-form">@csrf @method('PATCH')<label class="sr-only" for="role-{{ $person->id }}">{{ __('Role for :name', ['name' => $person->name]) }}</label><select class="form-input" name="role" id="role-{{ $person->id }}">@foreach(['reader' => 'Reader', 'premium-reader' => 'Premium reader', 'author' => 'Author', 'editor' => 'Editor'] + (auth()->user()->hasRole('super-admin') ? ['admin' => 'Admin'] : []) as $value => $label)<option value="{{ $value }}" @selected($person->hasRole($value) && ($value !== 'reader' || $person->roles->count() === 1))>{{ __($label) }}</option>@endforeach</select><label class="check-label"><input type="checkbox" name="suspended" value="1" @checked($person->suspended_at)> {{ __('Suspend') }}</label><button class="btn btn-outline" type="submit" aria-label="{{ __('Save access for :name', ['name' => $person->name]) }}">{{ __('Save') }}</button></form>@if(auth()->user()->hasRole('super-admin') && !$person->hasAnyRole(['admin','super-admin']) && !$person->suspended_at)<form method="POST" action="{{ route('support.start', $person) }}" class="support-session-form">@csrf<button class="text-button">{{ __('Open read-only support session') }}</button></form>@endif@else<span class="muted">{{ $person->getRoleNames()->map(fn($role) => __('ui.roles.'.$role))->join(', ') }}</span>@endif</td></tr>@empty<tr><td colspan="3">{{ __('No readers match your search. Try another name or email.') }}</td></tr>@endforelse</tbody></table></div>{{ $users->withQueryString()->fragment('people')->links() }}
    </section><section id="audit" class="admin-section"><h2>{{ __('Recent activity') }}</h2><p class="muted">{{ __('Recent administrative and publishing activity.') }}</p><div class="audit-list">@forelse($activities as $activity)<div><time datetime="{{ $activity->created_at->toIso8601String() }}">{{ $activity->created_at->format('M j, H:i') }}</time><p><strong>{{ $activity->causer?->name ?? __('System') }}</strong> · {{ $activity->description }}@if($activity->subject_id)<span class="muted"> · {{ class_basename($activity->subject_type) }} #{{ $activity->subject_id }}</span>@endif</p></div>@empty<p class="muted">{{ __('Your first administrative action will appear here.') }}</p>@endforelse</div></section>@endif
</div>
</x-layout>
