<x-layout :title="__('Writing studio')">
<div class="page-shell content-page">
 <div class="page-heading"><div><h1>{{ __('Writing studio') }}</h1><p>{{ __('Your drafts, published stories, and plans for what comes next.') }}</p></div><a href="/write" class="btn btn-primary"><x-icon name="pen-line" size="17" /> {{ __('New story') }}</a></div>
 <div class="dashboard-stats"><div><strong>{{ number_format($stats['views']) }}</strong><span>{{ __('Story views') }}</span></div><div><strong>{{ number_format($stats['followers']) }}</strong><span>{{ __('Followers') }}</span></div><div><strong>{{ number_format($stats['reactions']) }}</strong><span>{{ __('Appreciations') }}</span></div></div>
 <nav class="tab-nav" aria-label="{{ __('Filter your stories') }}">@foreach([''=>'All stories','published'=>'Published','draft'=>'Drafts','scheduled'=>'Scheduled','archived'=>'Archived'] as $status=>$label)<a href="{{ route('dashboard', $status ? ['status'=>$status] : []) }}" @class(['active'=>request('status','')===$status]) @if(request('status','')===$status) aria-current="page" @endif>{{ __($label) }}@if(in_array($status,['','published','draft']))<span class="count">{{ $stats[[''=>'posts','published'=>'published','draft'=>'drafts'][$status]] }}</span>@endif</a>@endforeach<a href="/series">{{ __('Collections') }} <x-icon name="book-open" size="14" /></a></nav>
 @if($posts->count())
 <div class="table-wrap studio-table-wrap"><table class="data-table studio-table"><caption class="sr-only">{{ __('Your stories and publishing status') }}</caption><thead><tr><th scope="col">{{ __('Story') }}</th><th scope="col">{{ __('Status') }}</th><th scope="col">{{ __('Views') }}</th><th scope="col">{{ __('Updated') }}</th><th scope="col"><span class="sr-only">{{ __('Actions') }}</span></th></tr></thead><tbody>
 @foreach($posts as $post)<tr><td class="studio-title"><h2><a href="/write/{{ $post->id }}">{{ $post->title }}</a></h2><p>{{ trans_choice('ui.reading_minutes', $post->reading_time) }} @if($post->is_premium) · {{ __('Members') }} @endif @if($post->status==='scheduled') · {{ __('Scheduled for') }} {{ $post->published_at?->format('M j, g:i A') }} {{ config('app.timezone') }} @endif</p></td><td class="studio-status"><span class="status-badge status-{{ $post->status }}">{{ __('ui.status.'.$post->status) }}</span></td><td class="studio-views"><span class="mobile-cell-label" aria-hidden="true">{{ __('Views') }} </span>{{ number_format($post->views) }}</td><td class="studio-updated"><span class="mobile-cell-label" aria-hidden="true">{{ __('Updated') }} </span><time datetime="{{ $post->updated_at->toIso8601String() }}">{{ $post->updated_at->format('M j, Y') }}</time></td><td class="studio-actions"><div class="table-actions"><a href="/write/{{ $post->id }}" class="btn btn-outline btn-small" aria-label="{{ __('Edit :title', ['title'=>$post->title]) }}">{{ $post->status==='archived' ? __('Open') : __('Edit') }}</a>@if($post->status==='published')<a href="{{ $post->url }}" class="icon-button" aria-label="{{ __('Read :title', ['title'=>$post->title]) }}" title="{{ __('Read story') }}"><x-icon name="arrow-up-right" size="19" /></a>@endif @if($post->status!=='archived')<form method="POST" action="/posts/{{ $post->id }}" data-confirm="{{ __('Archive this story? It will leave the public feed. You can restore it from Archived.') }}" onsubmit="return confirm(this.dataset.confirm)">@csrf @method('DELETE')<button class="icon-button" aria-label="{{ __('Archive :title', ['title'=>$post->title]) }}" title="{{ __('Archive story') }}"><x-icon name="archive" size="18" /></button></form>@endif</div></td></tr>@endforeach
 </tbody></table></div><div class="pagination-wrap">{{ $posts->links() }}</div>
 @else<div class="empty-state studio-empty"><x-icon name="pen-line" size="32" /><h2>{{ request('status') ? __('No :status stories.', ['status'=>strtolower(__('ui.status.'.request('status')))]) : __('Start your first story.') }}</h2><p>{{ request('status')==='scheduled' ? __('Set a date and time in your story’s Publish settings to schedule it.') : (request('status') ? __('Your stories will appear here when they have this status.') : __('Create a draft, take your time, and publish when you’re ready.')) }}</p><a href="{{ request('status') ? '/dashboard' : '/write' }}" class="btn btn-outline">{{ request('status') ? __('View all stories') : __('New story') }}</a></div>@endif
</div>
</x-layout>
