<x-layout :title="request()->routeIs('trending') ? __('Trending stories') : ($query ? __('Search: :query', ['query' => $query]) : __('A world of perspectives'))" :collection="['posts' => $posts]">
<div class="page-shell content-page"><div class="page-heading"><div><h1>{{ request()->routeIs('trending') ? __('The conversation starters.') : __('Follow your curiosity.') }}</h1><p>{{ request()->routeIs('trending') ? __('The stories finding their way into more minds.') : __('Find a new perspective, your next favorite writer, or an idea worth keeping.') }}</p></div></div>
<form id="discovery-search" class="search-form" action="/explore" method="GET" role="search"><x-icon name="search" size="22" /><label for="search-query" class="sr-only">{{ __('Search stories, topics, and writers') }}</label><input id="search-query" type="search" name="q" value="{{ $query }}" placeholder="{{ __('Stories, topics, and curious minds…') }}" maxlength="200"><button class="btn btn-primary" type="submit">{{ __('Search') }}</button></form>
<nav class="tab-nav" aria-label="{{ __('Search type') }}"><a href="{{ route('discover', ['q'=>$query]) }}" @class(['active'=>request('type')!=='people'])>{{ __('Stories') }}</a><a href="{{ route('discover', ['q'=>$query, 'type'=>'people']) }}" @class(['active'=>request('type')==='people'])>{{ __('Writers') }}</a></nav>
@if(request('type')==='people')<input form="discovery-search" type="hidden" name="type" value="people"><div class="writers-grid">@forelse($writers as $writer)<article class="writer-discovery"><x-avatar :user="$writer" size="large" /><h2><a href="{{ '/@'.$writer->username }}">{{ $writer->name }}</a></h2><p>{{ $writer->bio }}</p><span>{{ trans_choice('ui.story_count', $writer->posts_count) }} · {{ trans_choice('ui.follower_count', $writer->followers_count) }}</span><a href="{{ '/@'.$writer->username }}" class="text-link">{{ __('Meet :name', ['name' => explode(' ', $writer->name)[0]]) }} <x-icon name="arrow-up-right" size="15" /></a></article>@empty<div class="empty-state"><h2>{{ __('A new voice is around the corner.') }}</h2><p>{{ __('Try another name or topic to find a writer.') }}</p></div>@endforelse</div>{{ $writers->links() }}
@else
<nav class="topic-strip" aria-label="{{ __('Topics') }}"><a href="/explore" @class(['selected' => !request('topic')])>{{ __('All stories') }}</a>@foreach($topics as $topic)<a href="{{ route('discover', ['topic' => $topic->slug, 'q' => $query ?: null]) }}" @class(['selected' => request('topic') === $topic->slug])>{{ $topic->name }}</a>@endforeach</nav>
@if($query)<p class="muted" style="margin-top:24px;font-size:13px">{{ trans_choice('ui.search_story_count', $posts->total(), ['query' => $query]) }}</p>@endif
<div class="explore-grid">@forelse($posts as $post)<x-post-card :post="$post" />@empty<div class="empty-state"><x-icon name="search" size="32" /><h2>{{ __('A different word might open a new door.') }}</h2><p>{{ __('No stories matched this search. Try a broader topic or explore all stories.') }}</p><a href="/explore" class="btn btn-outline">{{ __('Explore all stories') }}</a></div>@endforelse</div><div class="pagination-wrap">{{ $posts->links() }}</div>@endif</div>
</x-layout>
