@php($trending = request()->routeIs('trending'))
@php($people = request('type') === 'people')
@php($browseRoute = $trending ? 'trending' : 'discover')
<x-layout :title="$trending ? __('Trending stories') : ($query !== '' ? __('Search: :query', ['query' => $query]) : __('Explore Folkscript'))" :collection="['posts' => $posts]">
<div class="page-shell content-page">
 <div class="page-heading"><div><h1>{{ $trending ? __('Trending stories') : __('Find your next read.') }}</h1><p>{{ $trending ? __('The most-read stories on Folkscript.') : __('Browse a subject you know, or follow a writer you haven’t met.') }}</p></div></div>
 <form id="discovery-search" class="search-form" action="{{ route($browseRoute) }}" method="GET" role="search"><x-icon name="search" size="22" /><label for="search-query" class="sr-only">{{ $people ? __('Search writers') : __('Search stories and topics') }}</label><input id="search-query" type="search" name="q" value="{{ $query }}" placeholder="{{ $people ? __('Search by name or biography') : __('Search stories, subjects, or writers') }}" maxlength="200">@if($people)<input type="hidden" name="type" value="people">@elseif(request('topic'))<input type="hidden" name="topic" value="{{ request('topic') }}">@endif<button class="btn btn-primary" type="submit">{{ __('Search') }}</button></form>
 @unless($trending)<nav class="tab-nav" aria-label="{{ __('Search type') }}"><a href="{{ route('discover', ['q'=>$query !== '' ? $query : null, 'topic'=>request('topic')]) }}" @class(['active'=>!$people]) @if(!$people) aria-current="page" @endif>{{ __('Stories') }}</a><a href="{{ route('discover', ['q'=>$query !== '' ? $query : null, 'type'=>'people']) }}" @class(['active'=>$people]) @if($people) aria-current="page" @endif>{{ __('Writers') }}</a></nav>@endunless
 @if($people && !$trending)
  <div class="results-summary"><p>{{ trans_choice('ui.writer_count', $writers->total()) }}@if($query !== '') {{ __('for “:query”', ['query'=>$query]) }}@endif</p>@if($query !== '')<a href="/explore?type=people">{{ __('Clear search') }}</a>@endif</div>
  <div class="writers-grid">@forelse($writers as $writer)<article class="writer-discovery"><x-avatar :user="$writer" size="large" /><h2><a href="{{ '/@'.$writer->username }}">{{ $writer->name }}</a></h2><p>{{ $writer->bio }}</p><span>{{ trans_choice('ui.story_count', $writer->posts_count) }} · {{ trans_choice('ui.follower_count', $writer->followers_count) }}</span><a href="{{ '/@'.$writer->username }}" class="text-link">{{ __('View profile') }} <x-icon name="arrow-up-right" size="15" /></a></article>@empty<div class="empty-state"><h2>{{ __('No writers found.') }}</h2><p>{{ __('Try a different name or a broader subject.') }}</p><a href="/explore?type=people" class="btn btn-outline">{{ __('Browse all writers') }}</a></div>@endforelse</div><div class="pagination-wrap">{{ $writers->links() }}</div>
 @else
  <nav class="topic-strip" aria-label="{{ __('Filter by topic') }}"><a href="{{ route($browseRoute, ['q' => $query !== '' ? $query : null]) }}" @class(['selected' => !request('topic')]) @if(!request('topic')) aria-current="page" @endif>{{ __('All topics') }}</a>@foreach($topics as $topic)<a href="{{ route($browseRoute, ['topic' => $topic->slug, 'q' => $query !== '' ? $query : null]) }}" @class(['selected' => request('topic') === $topic->slug]) @if(request('topic') === $topic->slug) aria-current="page" @endif>{{ $topic->name }}</a>@endforeach</nav>
  <div class="results-summary"><p>{{ $query !== '' ? trans_choice('ui.search_story_count', $posts->total(), ['query' => $query]) : trans_choice('ui.story_count', $posts->total()) }}</p>@if($query !== '' || request('topic'))<a href="{{ route($browseRoute) }}">{{ __('Clear filters') }}</a>@endif</div>
  <div class="explore-grid">@forelse($posts as $post)<x-post-card :post="$post" heading="h2" />@empty<div class="empty-state"><x-icon name="search" size="32" /><h2>{{ __('No stories found.') }}</h2><p>{{ __('Try fewer words, choose another topic, or clear your filters.') }}</p><a href="{{ route($browseRoute) }}" class="btn btn-outline">{{ __('Browse all stories') }}</a></div>@endforelse</div><div class="pagination-wrap">{{ $posts->links() }}</div>
 @endif
</div>
</x-layout>
