<x-layout title="{{ __('Your approved earnings') }}">
<div class="page-shell platform-page">
    <header class="page-heading"><div><h1>{{ __('Your approved earnings.') }}</h1><p class="muted">{{ __('A clear record of allocations and transfers.') }}</p></div><a href="{{ route('dashboard') }}" class="btn btn-outline">{{ __('Writing studio') }}</a></header>
    <p class="platform-intro">{{ __('Earnings appear here after the platform approves an allocation. Story views and reactions do not automatically earn money. Transferred funds go to your connected Stripe account; Stripe manages payment to your bank.') }}</p>
    <section class="platform-connect" aria-labelledby="connect-title"><div><h2 id="connect-title">{{ __('Your payout account') }}</h2><p class="muted">{{ $user->stripe_connect_id ? __('A Stripe account is linked. You may still need to complete verification before receiving transfers.') : __('Connect a Stripe account to receive approved earnings.') }}</p></div>@if($user->canWrite())<form method="post" action="{{ route('membership.connect') }}">@csrf<button class="btn btn-outline" type="submit">{{ $user->stripe_connect_id ? __('Review Stripe setup') : __('Connect with Stripe') }}</button></form>@endif</section>
    @if($totals->isNotEmpty())<div class="platform-balances">@foreach($totals as $currency => $entries)<div><h2>{{ strtoupper($currency) }}</h2><dl><div><dt>{{ __('Approved, not yet transferred') }}</dt><dd>{{ number_format($entries->where('status', '!=', 'paid')->sum('total_cents') / 100, 2) }}</dd></div><div><dt>{{ __('Transferred to Stripe') }}</dt><dd>{{ number_format($entries->where('status', 'paid')->sum('total_cents') / 100, 2) }}</dd></div></dl></div>@endforeach</div>@endif
    <section aria-labelledby="your-ledger-title"><h2 class="platform-ledger-heading" id="your-ledger-title">{{ __('Your ledger') }}</h2>
        @if($payouts->isNotEmpty())<div class="table-wrap" tabindex="0" aria-label="{{ __('Your earnings ledger') }}"><table class="data-table platform-ledger"><thead><tr><th scope="col">{{ __('Date') }}</th><th scope="col">{{ __('Reference') }}</th><th scope="col">{{ __('Amount') }}</th><th scope="col">{{ __('Status') }}</th></tr></thead><tbody>@foreach($payouts as $payout)<tr><td>{{ $payout->created_at->format('M j, Y') }}</td><td>{{ $payout->reference }}</td><td class="platform-amount">{{ $payout->formattedAmount() }}</td><td><span class="status-badge">{{ $payout->status === 'failed' ? __('Awaiting administrator review') : __('ui.payout_status.'.$payout->status) }}</span>@if($payout->paid_at)<p>{{ $payout->paid_at->format('M j, Y') }}</p>@endif</td></tr>@endforeach</tbody></table></div><div class="pagination-wrap">{{ $payouts->links() }}</div>
        @else<div class="empty-state"><h3>{{ __('No approved earnings yet.') }}</h3><p>{{ __('Any future allocations approved by the platform will appear here, along with their transfer status.') }}</p></div>@endif
    </section>
</div>
</x-layout>
