<x-layout>
<div class="page-shell">
 <div class="edition-line"><span>A home for independent minds.</span><span>{{ now()->format('l, F j') }} <span class="edition-dot"></span> A fresh perspective, every day</span></div>
 <section class="home-intro"><h1>Good stories.<br>A <em>wider</em> world.</h1><div><p>Ideas that stay with you. Voices you haven’t met.<br> A space for a little more perspective.</p><a class="text-link" href="#latest">Find your next good read <x-icon name="arrow-down" size="17" /></a></div></section>
 @if($featured)
 <section class="lead-story" aria-label="Featured story">
   <a class="lead-image" href="{{ $featured->url }}"><img src="{{ $featured->cover_url }}" alt="A quiet alpine lake reflecting mountains in the morning light" width="1000" height="700" fetchpriority="high"><span class="image-caption">A moment worth slowing down for.</span></a>
   <div class="lead-copy"><div class="lead-title-group"><h2><a href="{{ $featured->url }}">{{ $featured->title }}</a></h2><p>{{ $featured->excerpt }}</p></div><div><a class="lead-author" href="{{ '/@'.$featured->author->username }}"><x-avatar :user="$featured->author" /><div><strong>{{ $featured->author->name }}</strong><span>{{ $featured->published_at?->format('M j') }} <span>·</span> {{ $featured->reading_time }} min read</span></div></a><div class="lead-bottom"><span><x-icon name="feather" size="15" /> The editor’s pick</span><a href="{{ $featured->url }}" class="round-link" aria-label="Read {{ $featured->title }}"><x-icon name="arrow-up-right" size="25" /></a></div></div></div>
 </section>
 @endif
 <nav class="topic-strip" aria-label="Browse topics"><a @class(['selected'=>request('feed')!=='following']) href="/">For the curious</a>@auth<a href="/?feed=following" @class(['selected'=>request('feed')==='following'])>Following</a>@endauth@foreach($topics->take(7) as $topic)<a href="/topic/{{ $topic->slug }}">{{ $topic->name }}</a>@endforeach<a class="topic-more" href="/explore">All topics <x-icon name="arrow-right" size="16" /></a></nav>
 <div class="editorial-grid" id="latest">
  <section class="latest-section"><div class="section-heading"><h2>{{ request('feed')==='following' ? 'From your people' : 'Worth your time' }}</h2><a href="/explore" class="text-link">View all stories <x-icon name="arrow-up-right" size="15" /></a></div><div class="stories-grid">@forelse($posts as $post)<x-post-card :post="$post" />@empty<div class="empty-state"><x-icon name="book-open" size="32" /><h3>The next chapter starts with you.</h3><p>Share the first story with this community.</p><a href="/write" class="btn btn-primary">Write a story</a></div>@endforelse</div><div class="pagination-wrap">{{ $posts->links() }}</div></section>
  <aside class="editorial-sidebar"><section class="sidebar-note"><x-icon name="sparkles" size="25" /><h2>Good writing deserves good company.</h2><p>Join a community of curious readers and independent voices.</p><a class="btn btn-primary" href="/register">Find your people <x-icon name="arrow-up-right" size="17" /></a><span>Free to read. Free to begin.</span></section>
   <section class="writers-section"><div class="section-heading"><h2>Voices to know</h2></div>@foreach($suggestedAuthors->take(4) as $writer)<div class="suggested-writer"><a href="{{ '/@'.$writer->username }}"><x-avatar :user="$writer" /><div><strong>{{ $writer->name }}</strong><span>{{ Str::limit($writer->bio ?? 'An independent voice on Folkscript.', 48) }}</span></div></a>@auth<form method="POST" action="/authors/{{ $writer->id }}/follow">@csrf<button class="icon-button" aria-label="Follow {{ $writer->name }}"><x-icon name="plus" size="19" /></button></form>@else<a href="/login" class="icon-button" aria-label="Follow {{ $writer->name }}"><x-icon name="plus" size="19" /></a>@endauth</div>@endforeach<a href="/explore?type=people" class="text-link sidebar-link">Meet more writers <x-icon name="arrow-right" size="15" /></a></section>
   <div class="sidebar-small"><span class="small-rule"></span><p>“There is no greater agony than bearing an untold story inside you.”</p><span>— Maya Angelou</span></div>
  </aside>
 </div>
 <section class="closing-invitation"><div><h2>Everyone has a story.<br><em>What’s yours?</em></h2><p>A thought, a discovery, a different way of seeing.<br>There’s room for your voice here.</p></div><a href="/write" class="btn btn-paper">Put it into words <x-icon name="arrow-up-right" size="19" /></a><img src="/images/folkscript-mark-standalone.svg" alt="" class="invitation-mark" width="180" height="180"></section>
</div>
</x-layout>
