<x-layout>
@php($following = request('feed') === 'following' && auth()->check())
<div class="page-shell">
 @if(!$following && $posts->currentPage() === 1)
 <section class="home-intro"><h1>Good stories.<br>A <em>wider</em> world.</h1><div><p>{{ __('Essays, ideas, and observations from independent writers. Every story is free to read.') }}</p><a class="text-link" href="#latest">{{ __('Browse the latest stories') }} <x-icon name="arrow-down" size="17" /></a></div></section>
 @if($featured)
 <section class="lead-story" aria-label="{{ __('Featured story') }}">
   <a class="lead-image" href="{{ $featured->url }}" tabindex="-1" aria-hidden="true"><img src="{{ $featured->cover_url }}" alt="" width="1000" height="700" fetchpriority="high"></a>
   <div class="lead-copy"><div class="lead-title-group"><h2><a href="{{ $featured->url }}">{{ $featured->title }}</a></h2><p>{{ $featured->excerpt }}</p></div><div><a class="lead-author" href="{{ '/@'.$featured->author->username }}"><x-avatar :user="$featured->author" /><div><strong>{{ $featured->author->name }}</strong><span>{{ $featured->published_at?->format('M j') }} <span>·</span> {{ trans_choice('ui.reading_minutes', $featured->reading_time) }}</span></div></a><div class="lead-bottom"><span>{{ __('Featured story') }}</span><a href="{{ $featured->url }}" class="text-link">{{ __('Read story') }} <x-icon name="arrow-up-right" size="19" /></a></div></div></div>
 </section>
 @endif
 @else
 <div class="page-heading"><div><h1>{{ $following ? __('Following') : __('Latest stories') }}</h1><p>{{ $following ? __('New writing from the people and topics you follow.') : __('More essays, ideas, and observations from our writers.') }}</p></div><a class="text-link" href="/explore?type=people">{{ __('Find writers') }} <x-icon name="arrow-up-right" size="17" /></a></div>
 @endif
 <nav class="topic-strip" aria-label="{{ __('Browse stories and topics') }}"><a @class(['selected'=>!$following]) @if(!$following) aria-current="page" @endif href="/#latest">{{ __('Latest') }}</a>@auth<a href="/?feed=following" @class(['selected'=>$following]) @if($following) aria-current="page" @endif>{{ __('Following') }}</a>@endauth@foreach($topics->take(7) as $topic)<a href="/topic/{{ $topic->slug }}">{{ $topic->name }}</a>@endforeach<a class="topic-more" href="/explore">{{ __('All topics') }} <x-icon name="arrow-right" size="16" /></a></nav>
 <div class="editorial-grid" id="latest">
  <section class="latest-section"><div class="section-heading"><h2>{{ $following ? __('Your feed') : __('The latest') }}</h2><a href="/explore" class="text-link">{{ __('Explore all') }} <x-icon name="arrow-up-right" size="15" /></a></div><div class="home-story-list">@forelse($posts as $post)<x-post-card :post="$post" compact />@empty<div class="empty-state"><x-icon name="book-open" size="32" /><h3>{{ $following ? __('Make this feed your own.') : __('No stories here yet.') }}</h3><p>{{ $following ? __('Follow a writer or a topic. Their new stories will appear here as they publish.') : __('Published stories will appear here. You can start the first one.') }}</p><a href="{{ $following ? '/explore?type=people' : '/write' }}" class="btn btn-primary">{{ $following ? __('Find writers to follow') : __('Write a story') }}</a></div>@endforelse</div><div class="pagination-wrap">{{ $posts->fragment('latest')->links() }}</div></section>
  <aside class="editorial-sidebar">
   <section class="sidebar-note">
    @auth<h2>{{ __('Keep your next read close.') }}</h2><p>{{ __('Save a story with the bookmark beside it. Your reading list is always here when you return.') }}</p><a class="btn btn-outline" href="/bookmarks">{{ __('Saved stories') }} <x-icon name="bookmark" size="17" /></a>
    @else<h2>{{ __('Read. Save. Come back.') }}</h2><p>{{ __('Create a free account to save stories, follow writers, and join the conversation.') }}</p><a class="btn btn-primary" href="/register">{{ __('Create an account') }} <x-icon name="arrow-up-right" size="17" /></a><span>{{ __('Already a reader?') }} <a href="/login">{{ __('Sign in') }}</a></span>@endauth
   </section>
   <section class="writers-section"><div class="section-heading"><h2>{{ __('Writers to discover') }}</h2></div>@foreach($suggestedAuthors->take(4) as $writer)<div class="suggested-writer"><a href="{{ '/@'.$writer->username }}"><x-avatar :user="$writer" /><div><strong>{{ $writer->name }}</strong><span>{{ Str::limit($writer->bio ?? '', 64) }}</span></div></a>@auth<form method="POST" action="/authors/{{ $writer->id }}/follow" data-toggle-action="follow" data-label-on="{{ __('Unfollow :name', ['name' => $writer->name]) }}" data-label-off="{{ __('Follow :name', ['name' => $writer->name]) }}">@csrf<button class="icon-button {{ $writer->is_followed ? 'engaged' : '' }}" aria-pressed="{{ $writer->is_followed ? 'true' : 'false' }}" aria-label="{{ $writer->is_followed ? __('Unfollow :name', ['name' => $writer->name]) : __('Follow :name', ['name' => $writer->name]) }}"><x-icon :name="$writer->is_followed ? 'check' : 'plus'" size="19" /></button></form>@else<a href="{{ route('login', ['return_to' => '/@'.$writer->username]) }}" class="icon-button" aria-label="{{ __('Follow :name', ['name' => $writer->name]) }}"><x-icon name="plus" size="19" /></a>@endauth</div>@endforeach<a href="/explore?type=people" class="text-link sidebar-link">{{ __('Browse all writers') }} <x-icon name="arrow-right" size="15" /></a></section>
   <section class="sidebar-topics"><h2>{{ __('Pick a subject') }}</h2>@foreach($topics as $topic)<a href="/topic/{{ $topic->slug }}"><span>{{ $topic->name }}</span><span>{{ $topic->posts_count }}</span></a>@endforeach</section>
  </aside>
 </div>
 @guest<section class="closing-invitation"><div><h2>{{ __('Something to say?') }}<br><em>{{ __('Start with a draft.') }}</em></h2><p>{{ __('Write at your own pace. Publish when you’re ready.') }}</p></div><a href="/write" class="btn btn-paper">{{ __('Start writing') }} <x-icon name="arrow-up-right" size="19" /></a></section>@endguest
</div>
</x-layout>
