<x-layout title="{{ __('A membership for curious minds') }}">
<div class="page-shell membership-page">
    <header class="membership-intro"><h1>{{ __('Good writing is') }}<br>{{ __('worth keeping alive.') }}</h1><p>{{ __('Make room for independent voices, thoughtful ideas, and stories that stay with you.') }}</p></header>
    @if(request('checkout') === 'complete')<div class="notice" role="status">{{ __('Thank you. Your payment is being confirmed. Membership access updates automatically once Stripe confirms your subscription.') }}</div>@endif
    @if($user?->hasPremiumAccess())<div class="membership-current"><div><h2>{{ __('You’re part of the story.') }}</h2><p>{{ __('Your membership gives you access to every members-only story.') }}</p></div>@if($user->stripe_id && config('cashier.secret'))<form method="post" action="{{ route('membership.portal') }}">@csrf<button class="btn btn-outline" type="submit">{{ __('Manage membership') }}</button></form>@endif</div>@endif
    <div class="membership-options">
        <section class="membership-free"><h2>{{ __('A place for everyone.') }}</h2><div class="membership-price">{{ __('Free') }}<span>{{ __('Always a good place to start.') }}</span></div><p>{{ __('Discover your next favorite writer and join an open community of curious people.') }}</p><ul class="membership-features"><li>{{ __('Read every open-access story') }}</li><li>{{ __('Save stories for a quiet moment') }}</li><li>{{ __('Follow writers and join conversations') }}</li><li>{{ __('Publish your own words after verification') }}</li></ul>@guest<a href="{{ route('register') }}" class="btn btn-outline">{{ __('Create a free account') }}</a>@else<a href="/explore" class="btn btn-outline">{{ __('Find your next read') }} <span aria-hidden="true">→</span></a>@endguest</section>
        <section class="membership-paid"><div class="membership-mark" aria-hidden="true">F.</div><h2>{{ __('Go a little deeper.') }}</h2>
            @if($billingReady)<div class="membership-price">${{ config('services.stripe.membership_monthly', 8) }}<span>{{ __('per month · cancel anytime') }}</span></div>@else<div class="membership-price membership-coming">{{ __('Membership') }}<span>{{ __('Opening soon.') }}</span></div>@endif
            <p>{{ __('For the readers who believe in the people behind the words.') }}</p><ul class="membership-features"><li>{{ __('Everything in your free account') }}</li><li>{{ __('Access to all members-only stories') }}</li><li>{{ __('More room for independent publishing') }}</li><li>{{ __('Simple, secure billing through Stripe') }}</li></ul>
            @if($billingReady && ! $user?->hasPremiumAccess())@auth @if(!$user->hasVerifiedEmail())<p class="membership-note">{{ __('Verify your email before becoming a member.') }}</p><a href="{{ route('verification.notice') }}" class="btn btn-primary">{{ __('Verify email') }}</a>@else<form method="post" action="{{ route('membership.checkout') }}" class="stack">@csrf<label class="field">{{ __('Choose your membership') }}<select aria-invalid="{{ $errors->getBag('default')->has('plan') ? 'true' : 'false' }}" aria-describedby="membership1-error" class="form-input" name="plan"><option value="monthly">{{ __('Monthly · $:amount', ['amount' => config('services.stripe.membership_monthly', 8)]) }}</option>@if(config('services.stripe.yearly_price'))<option value="yearly">{{ __('Yearly · $:amount', ['amount' => config('services.stripe.membership_yearly', 80)]) }}</option>@endif</select><x-field-error name="plan" bag="default" id="membership1-error" /></label><button class="btn btn-primary" type="submit">{{ __('Become a member') }} <span aria-hidden="true">→</span></button></form>@endif @else<a href="{{ route('register') }}" class="btn btn-primary">{{ __('Join Folkscript') }}</a>@endauth
            @elseif(! $billingReady)<p class="membership-note">{{ __('We’re getting memberships ready. Until then, there’s a whole world of open stories to explore.') }}</p><a href="/explore" class="btn btn-primary">{{ __('Explore the stories') }} <span aria-hidden="true">→</span></a>@else<span class="membership-note">{{ __('Your membership is active. Happy reading.') }}</span>@endif
        </section>
    </div>
    @auth @if($user->canWrite())<section class="creator-membership"><div><h2>{{ __('Your work. Your next chapter.') }}</h2><p class="muted">{{ __('Connect a Stripe account to prepare for creator payouts. Your banking details stay with Stripe.') }}</p>@if($connect)<p class="account-status">{{ $connect['enabled'] ? __('Payout account connected') : __('Finish your payout account setup') }}</p><div class="creator-balances">@foreach($connect['available'] as $balance)<div><strong>{{ number_format($balance->amount / 100, 2) }} {{ strtoupper($balance->currency) }}</strong><span>{{ __('Available in your Stripe account') }}</span></div>@endforeach @foreach($connect['pending'] as $balance)<div><strong>{{ number_format($balance->amount / 100, 2) }} {{ strtoupper($balance->currency) }}</strong><span>{{ __('Pending in your Stripe account') }}</span></div>@endforeach</div>@endif</div>@if(config('cashier.secret'))<form method="post" action="{{ route('membership.connect') }}">@csrf<button class="btn btn-outline" type="submit">{{ $user->stripe_connect_id ? __('Manage payout setup') : __('Set up creator payouts') }} <span aria-hidden="true">↗</span></button></form>@else<p class="creator-unavailable">{{ __('Creator payouts are not open yet. Your approved earnings will appear in your ledger when available.') }} <a href="{{ route('earnings') }}">{{ __('View earnings') }}</a></p>@endif</section>@endif @endauth
    <section class="membership-faq"><h2>{{ __('A few things you might wonder.') }}</h2><details><summary>{{ __('Can I keep reading for free?') }}</summary><p>{{ __('Absolutely. Open-access stories are available to everyone. A free account lets you save stories, follow authors, and join conversations.') }}</p></details><details><summary>{{ __('Can I publish on Folkscript?') }}</summary><p>{{ __('Yes. Create a free account and verify your email. You can then write, publish, schedule stories, and build your own readership.') }}</p></details><details><summary>{{ __('How do I manage my subscription?') }}</summary><p>{{ __('Once memberships open, subscribers can manage billing and cancel at any time through the secure Stripe billing portal on this page.') }}</p></details></section>
</div>
</x-layout>
