<x-layout title="{{ __('Your settings') }}">
<div class="page-shell account-page">
    <header class="page-heading"><div><h1>{{ __('Settings') }}</h1><p class="muted">{{ __('Manage your profile, privacy, and account security.') }}</p></div><a href="{{ url('/@'.$user->username) }}" class="btn btn-outline">{{ __('View your profile') }} <span aria-hidden="true">↗</span></a></header>
    <div class="settings-layout">
        <nav class="settings-nav settings-section-nav" aria-label="{{ __('Settings sections') }}"><a href="#profile">{{ __('Profile') }}</a><a href="#preferences">{{ __('Email preferences') }}</a><a href="#featured-story">{{ __('Featured story') }}</a><a href="#security">{{ __('Security') }}</a><a href="#api">{{ __('API access') }}</a></nav>
        <div class="settings-content">
            <section id="profile" class="settings-section"><h2>{{ __('Your public profile') }}</h2><p class="muted">{{ __('Help readers get to know the person behind the words.') }}</p>
                <form method="post" action="{{ route('settings.update') }}" enctype="multipart/form-data" class="stack">@csrf @method('PATCH')
                    <div class="profile-photo-editor"><x-avatar :user="$user" class="account-avatar" /><label class="field">{{ __('Profile photo') }}<input aria-invalid="{{ $errors->getBag('default')->has('avatar') ? 'true' : 'false' }}" aria-describedby="settings1-help settings1-error" class="form-input" type="file" name="avatar" accept="image/jpeg,image/png,image/webp"><span class="field-help" id="settings1-help">{{ __('JPG, PNG, or WebP. Up to 4 MB.') }}</span><x-field-error name="avatar" bag="default" id="settings1-error" /></label></div>@if($user->avatar)<label class="check-label"><input type="checkbox" name="remove_avatar" value="1">{{ __('Remove current profile photo') }}</label>@endif
                    <div class="form-grid"><label class="field">{{ __('Display name') }}<input aria-invalid="{{ $errors->getBag('default')->has('name') ? 'true' : 'false' }}" aria-describedby="settings2-error" class="form-input" autocomplete="name" name="name" value="{{ old('name', $user->name) }}" maxlength="80" required><x-field-error name="name" bag="default" id="settings2-error" /></label><label class="field">{{ __('Username') }}<input aria-invalid="{{ $errors->getBag('default')->has('username') ? 'true' : 'false' }}" aria-describedby="settings3-help settings3-error" class="form-input" autocomplete="username" autocapitalize="none" spellcheck="false" minlength="3" maxlength="30" name="username" value="{{ old('username', $user->username) }}" pattern="[a-z0-9_]{3,30}" required><span class="field-help" id="settings3-help">{{ __('3–30 lowercase letters, numbers, or underscores. Your profile address changes with your username; old links redirect automatically.') }}</span><x-field-error name="username" bag="default" id="settings3-error" /></label></div>
                    <label class="field">{{ __('A little about you') }}<textarea aria-invalid="{{ $errors->getBag('default')->has('bio') ? 'true' : 'false' }}" aria-describedby="settings4-help settings4-error" class="form-input" name="bio" rows="4" maxlength="500" placeholder="{{ __('What do you write about? What keeps you curious?') }}">{{ old('bio', $user->bio) }}</textarea><span class="field-help" id="settings4-help">{{ __('Up to 500 characters.') }}</span><x-field-error name="bio" bag="default" id="settings4-error" /></label>
                    <div class="form-grid"><label class="field">{{ __('Location') }}<input aria-invalid="{{ $errors->getBag('default')->has('location') ? 'true' : 'false' }}" aria-describedby="settings5-error" class="form-input" name="location" value="{{ old('location', $user->location) }}" maxlength="100" placeholder="{{ __('City, country') }}"><x-field-error name="location" bag="default" id="settings5-error" /></label><label class="field">{{ __('Your website') }}<input aria-invalid="{{ $errors->getBag('default')->has('website') ? 'true' : 'false' }}" aria-describedby="settings6-error" class="form-input" type="url" name="website" value="{{ old('website', $user->social_links['website'] ?? '') }}" placeholder="https://"><x-field-error name="website" bag="default" id="settings6-error" /></label></div>
                    <div class="form-grid"><label class="field">{{ __('GitHub profile') }}<input aria-invalid="{{ $errors->getBag('default')->has('github') ? 'true' : 'false' }}" aria-describedby="settings7-error" class="form-input" type="url" name="github" value="{{ old('github', $user->social_links['github'] ?? '') }}" placeholder="https://github.com/yourname"><x-field-error name="github" bag="default" id="settings7-error" /></label><label class="field">{{ __('LinkedIn profile') }}<input aria-invalid="{{ $errors->getBag('default')->has('linkedin') ? 'true' : 'false' }}" aria-describedby="settings8-error" class="form-input" type="url" name="linkedin" value="{{ old('linkedin', $user->social_links['linkedin'] ?? '') }}" placeholder="https://linkedin.com/in/yourname"><x-field-error name="linkedin" bag="default" id="settings8-error" /></label></div>
                    @if($user->cover_image)<img class="settings-cover-preview" src="{{ $user->cover_image }}" alt="{{ __('Your current profile cover') }}" loading="lazy">@endif<label class="field">{{ __('Profile cover') }}<input aria-invalid="{{ $errors->getBag('default')->has('cover_image') ? 'true' : 'false' }}" aria-describedby="settings9-help settings9-error" class="form-input" type="file" name="cover_image" accept="image/jpeg,image/png,image/webp"><span class="field-help" id="settings9-help">{{ __('A wide image works best. Up to 6 MB.') }}</span><x-field-error name="cover_image" bag="default" id="settings9-error" /></label>@if($user->cover_image)<label class="check-label"><input type="checkbox" name="remove_cover_image" value="1">{{ __('Remove current profile cover') }}</label>@endif
                    <input type="hidden" name="newsletter_enabled" value="0"><div id="preferences" class="settings-preference"><div><h3>{{ __('Email digests') }}</h3><p class="muted">{{ __('Receive email digests with new stories from writers you follow.') }}</p></div><label class="check-label"><input type="checkbox" name="newsletter_enabled" value="1" @checked(old('newsletter_enabled', $user->newsletter_enabled))> {{ __('Email digests') }}</label></div>
                    <button class="btn btn-primary" type="submit">{{ __('Save profile and preferences') }}</button>
                </form>
            </section>
            <section id="featured-story" class="settings-section"><h2>{{ __('Featured story') }}</h2><p class="muted">{{ __('Pin one published story to the top of your profile. Choose the piece that feels most like you.') }}</p><form method="post" action="{{ route('settings.pinned-story') }}" class="inline-form">@csrf<label class="field">{{ __('Featured story') }}<select aria-invalid="{{ $errors->getBag('default')->has('post_id') ? 'true' : 'false' }}" aria-describedby="settings10-error" class="form-input" name="post_id"><option value="">{{ __('No pinned story') }}</option>@foreach($pinnablePosts as $pinnable)<option value="{{ $pinnable->id }}" @selected((int) old('post_id', $user->pinned_post_id) === $pinnable->id)>{{ $pinnable->title }}</option>@endforeach</select><x-field-error name="post_id" bag="default" id="settings10-error" /></label><button class="btn btn-outline" type="submit">{{ __('Save featured story') }}</button></form>@if($pinnablePosts->isEmpty())<p class="muted">{{ __('Your published stories will appear here when you’re ready.') }}</p>@endif</section>
            <section id="security" class="settings-section"><h2>{{ __('Security') }}</h2><p class="muted">{{ __('Signed in as :email.', ['email' => $user->email]) }} @if($user->hasVerifiedEmail()){{ __('Email verified.') }}@else <a href="{{ route('verification.notice') }}">{{ __('Verify your email') }}</a> {{ __('to start publishing.') }}@endif</p>
                <details class="settings-disclosure" @if($errors->getBag('passwordChange')->any()) open @endif><summary>{{ __('Change password') }}</summary><form method="post" action="{{ route('settings.password') }}" class="stack" data-error-bag="passwordChange">@csrf @method('PUT')<label class="field">{{ __('Current password') }}<input aria-invalid="{{ $errors->getBag('passwordChange')->has('current_password') ? 'true' : 'false' }}" aria-describedby="settings11-error" class="form-input" type="password" name="current_password" autocomplete="current-password" required><x-field-error name="current_password" bag="passwordChange" id="settings11-error" /></label><div class="form-grid"><label class="field">{{ __('New password') }}<input aria-invalid="{{ $errors->getBag('passwordChange')->has('password') ? 'true' : 'false' }}" aria-describedby="settings12-help settings12-error" class="form-input" type="password" name="password" minlength="10" autocomplete="new-password" required><span class="field-help" id="settings12-help">{{ __('At least 10 characters, including a letter and number.') }}</span><x-field-error name="password" bag="passwordChange" id="settings12-error" /></label><label class="field">{{ __('Confirm password') }}<input aria-invalid="{{ $errors->getBag('passwordChange')->has('password_confirmation') ? 'true' : 'false' }}" aria-describedby="settings13-error" class="form-input" type="password" name="password_confirmation" autocomplete="new-password" required><x-field-error name="password_confirmation" bag="passwordChange" id="settings13-error" /></label></div><button class="btn btn-primary" type="submit">{{ __('Update password') }}</button></form></details>
                <div class="security-row"><div><h3>{{ __('Two-factor authentication') }}</h3><p class="muted">{{ __('An extra layer of protection with an authenticator app.') }}</p></div><span class="account-status">{{ $user->two_factor_confirmed_at ? __('Enabled') : ($user->two_factor_secret ? __('Setup incomplete') : __('Not enabled')) }}</span></div>
                @if(! $user->two_factor_secret)
                    <form method="post" action="{{ route('settings.two-factor.enable') }}">@csrf<button class="btn btn-outline" type="submit">{{ __('Set up two-factor authentication') }}</button></form>
                @elseif(time() - session('auth.password_confirmed_at', 0) > config('auth.password_timeout', 10800))
                    <a href="{{ route('password.confirm') }}" class="btn btn-outline">{{ __('Confirm password to manage security') }}</a>
                @else
                    @if(! $user->two_factor_confirmed_at)<div class="two-factor-setup"><div class="two-factor-qr">{!! $user->twoFactorQrCodeSvg() !!}</div><div><h3>{{ __('Connect your authenticator') }}</h3><p class="muted">{{ __('Scan this QR code, then enter the code shown in your app to finish setup.') }}</p><form method="post" action="{{ route('settings.two-factor.confirm') }}" class="stack" data-error-bag="confirmTwoFactorAuthentication">@csrf<label class="field">{{ __('Six-digit code') }}<input aria-invalid="{{ $errors->getBag('confirmTwoFactorAuthentication')->has('code') ? 'true' : 'false' }}" aria-describedby="settings14-error" class="form-input" name="code" maxlength="6" inputmode="numeric" pattern="[0-9]{6}" autocomplete="one-time-code" required><x-field-error name="code" bag="confirmTwoFactorAuthentication" id="settings14-error" /></label><button class="btn btn-primary" type="submit">{{ __('Confirm setup') }}</button></form></div></div>@else
                        <details class="settings-disclosure"><summary>{{ __('Show your recovery codes') }}</summary><p class="muted">{{ __('Keep these codes somewhere private. Each code can be used once if you lose your authenticator.') }}</p><div class="recovery-codes">@foreach($user->recoveryCodes() as $code)<code>{{ $code }}</code>@endforeach</div><form method="post" action="{{ route('settings.recovery-codes') }}">@csrf<button class="btn btn-outline" type="submit">{{ __('Generate new recovery codes') }}</button></form></details>
                    @endif
                    <form method="post" action="{{ route('settings.two-factor.disable') }}">@csrf @method('DELETE')<button class="text-button" type="submit">{{ $user->two_factor_confirmed_at ? __('Disable two-factor authentication') : __('Cancel setup') }}</button></form>
                @endif
            </section>
            <section id="api" class="settings-section"><h2>{{ __('API access') }}</h2><p class="muted">{{ __('Create a read-only token for the Folkscript API. Tokens expire after 90 days.') }}</p>
                @if(session('token'))<div class="notice"><strong>{{ __('Copy your token now') }}</strong><p>{{ __('It will only be shown once. Keep it private, like a password.') }}</p><code class="token-value">{{ session('token') }}</code></div>@endif
                @forelse($tokens as $token)<div class="security-row"><div><h3>{{ $token->name }}</h3><p class="muted">{{ __('Created :date', ['date' => $token->created_at->format('M j, Y')]) }} · {{ $token->last_used_at ? __('Last used :time', ['time' => $token->last_used_at->diffForHumans()]) : __('Not used yet') }}</p></div><form method="post" action="{{ route('settings.tokens.revoke', $token) }}">@csrf @method('DELETE')<button class="text-button" type="submit">{{ __('Revoke') }}</button></form></div>@empty<p class="muted">{{ __('You haven’t created any API tokens.') }}</p>@endforelse
                <form method="post" action="{{ route('settings.tokens.create') }}" class="inline-form">@csrf<label class="field">{{ __('Token name') }}<input aria-invalid="{{ $errors->getBag('default')->has('token_name') ? 'true' : 'false' }}" aria-describedby="settings15-error" class="form-input" name="token_name" value="{{ old('token_name') }}" maxlength="60" placeholder="{{ __('My reading app') }}" required><x-field-error name="token_name" bag="default" id="settings15-error" /></label><button class="btn btn-outline" type="submit">{{ __('Create token') }}</button></form>
            </section>
            <section class="settings-section"><details class="settings-disclosure danger-disclosure" @if($errors->getBag('accountDeletion')->any()) open @endif><summary>{{ __('Delete your account') }}</summary><p class="muted">{{ __('This permanently deletes your account and your stories. This action cannot be undone.') }}</p><form method="post" action="{{ route('settings.destroy') }}" class="stack" data-error-bag="accountDeletion">@csrf @method('DELETE')<label class="field">{{ __('Confirm your password') }}<input aria-invalid="{{ $errors->getBag('accountDeletion')->has('password') ? 'true' : 'false' }}" aria-describedby="settings16-error" class="form-input" type="password" name="password" autocomplete="current-password" required><x-field-error name="password" bag="accountDeletion" id="settings16-error" /></label><label class="field">{{ __('Type DELETE to confirm') }}<input aria-invalid="{{ $errors->getBag('accountDeletion')->has('confirmation') ? 'true' : 'false' }}" aria-describedby="settings17-error" class="form-input" name="confirmation" autocomplete="off" maxlength="6" pattern="DELETE" required><x-field-error name="confirmation" bag="accountDeletion" id="settings17-error" /></label><button class="btn btn-danger" type="submit">{{ __('Permanently delete account') }}</button></form></details></section>
        </div>
    </div>
</div>
</x-layout>
