<x-layout title="{{ __('Your settings') }}">
<div class="page-shell account-page">
    <header class="page-heading"><div><h1>{{ __('Your settings.') }}</h1><p class="muted">{{ __('A space that feels like you.') }}</p></div><a href="{{ url('/@'.$user->username) }}" class="btn btn-outline">{{ __('View your profile') }} <span aria-hidden="true">↗</span></a></header>
    <div class="settings-layout">
        <nav class="settings-nav" aria-label="{{ __('Settings sections') }}"><a href="#profile">{{ __('Profile') }}</a><a href="#security">{{ __('Security') }}</a><a href="#preferences">{{ __('Email preferences') }}</a><a href="#api">{{ __('API access') }}</a><a href="{{ route('membership') }}">{{ __('Membership ↗') }}</a></nav>
        <div class="settings-content">
            <section id="profile" class="settings-section"><h2>{{ __('Your public profile') }}</h2><p class="muted">{{ __('Help readers get to know the person behind the words.') }}</p>
                <form method="post" action="{{ route('settings.update') }}" enctype="multipart/form-data" class="stack">@csrf @method('PATCH')
                    <div class="profile-photo-editor">@if($user->avatar)<img class="account-avatar" src="{{ $user->avatar }}" alt="{{ __('Your current profile photo') }}" width="76" height="76">@else<div class="account-avatar account-initials">{{ $user->initials() }}</div>@endif<label class="field">{{ __('Profile photo') }}<input class="form-input" type="file" name="avatar" accept="image/jpeg,image/png,image/webp"><span class="field-help">{{ __('JPG, PNG, or WebP. Up to 4 MB.') }}</span></label></div>
                    <div class="form-grid"><label class="field">{{ __('Display name') }}<input class="form-input" name="name" value="{{ old('name', $user->name) }}" maxlength="80" required></label><label class="field">{{ __('Username') }}<input class="form-input" name="username" value="{{ old('username', $user->username) }}" pattern="[a-z0-9_]{3,30}" required><span class="field-help">folkscript.com/&#64;yourname</span></label></div>
                    <label class="field">{{ __('A little about you') }}<textarea class="form-input" name="bio" rows="4" maxlength="500" placeholder="{{ __('What do you write about? What keeps you curious?') }}">{{ old('bio', $user->bio) }}</textarea><span class="field-help">{{ __('Up to 500 characters.') }}</span></label>
                    <div class="form-grid"><label class="field">{{ __('Location') }}<input class="form-input" name="location" value="{{ old('location', $user->location) }}" maxlength="100" placeholder="{{ __('City, country') }}"></label><label class="field">{{ __('Your website') }}<input class="form-input" type="url" name="website" value="{{ old('website', $user->social_links['website'] ?? '') }}" placeholder="https://"></label></div>
                    <div class="form-grid"><label class="field">{{ __('GitHub profile') }}<input class="form-input" type="url" name="github" value="{{ old('github', $user->social_links['github'] ?? '') }}" placeholder="https://github.com/yourname"></label><label class="field">{{ __('LinkedIn profile') }}<input class="form-input" type="url" name="linkedin" value="{{ old('linkedin', $user->social_links['linkedin'] ?? '') }}" placeholder="https://linkedin.com/in/yourname"></label></div>
                    <label class="field">{{ __('Profile cover') }}<input class="form-input" type="file" name="cover_image" accept="image/jpeg,image/png,image/webp"><span class="field-help">{{ __('A wide image works best. Up to 6 MB.') }}</span></label>
                    <div id="preferences" class="settings-preference"><div><h3>{{ __('A little inspiration, occasionally.') }}</h3><p class="muted">{{ __('Receive email digests with new stories from writers you follow.') }}</p></div><label class="check-label"><input type="checkbox" name="newsletter_enabled" value="1" @checked(old('newsletter_enabled', $user->newsletter_enabled))> {{ __('Email digests') }}</label></div>
                    <button class="btn btn-primary" type="submit">{{ __('Save profile') }}</button>
                </form>
            </section>
            <section class="settings-section"><h2>{{ __('Give readers a place to start.') }}</h2><p class="muted">{{ __('Pin one published story to the top of your profile. Choose the piece that feels most like you.') }}</p><form method="post" action="{{ route('settings.pinned-story') }}" class="inline-form">@csrf<label class="field">{{ __('Featured story') }}<select class="form-input" name="post_id"><option value="">{{ __('No pinned story') }}</option>@foreach($pinnablePosts as $pinnable)<option value="{{ $pinnable->id }}" @selected((int) $user->pinned_post_id === $pinnable->id)>{{ $pinnable->title }}</option>@endforeach</select></label><button class="btn btn-outline" type="submit">{{ __('Save featured story') }}</button></form>@if($pinnablePosts->isEmpty())<p class="muted">{{ __('Your published stories will appear here when you’re ready.') }}</p>@endif</section>
            <section id="security" class="settings-section"><h2>{{ __('Keep your account yours.') }}</h2><p class="muted">{{ __('Signed in as :email.', ['email' => $user->email]) }} @if($user->hasVerifiedEmail()){{ __('Email verified.') }}@else <a href="{{ route('verification.notice') }}">{{ __('Verify your email') }}</a> {{ __('to start publishing.') }}@endif</p>
                <details class="settings-disclosure"><summary>{{ __('Change password') }}</summary><form method="post" action="{{ route('settings.password') }}" class="stack">@csrf @method('PUT')<label class="field">{{ __('Current password') }}<input class="form-input" type="password" name="current_password" autocomplete="current-password" required></label><div class="form-grid"><label class="field">{{ __('New password') }}<input class="form-input" type="password" name="password" minlength="10" autocomplete="new-password" required></label><label class="field">{{ __('Confirm password') }}<input class="form-input" type="password" name="password_confirmation" autocomplete="new-password" required></label></div><button class="btn btn-primary" type="submit">{{ __('Update password') }}</button></form></details>
                <div class="security-row"><div><h3>{{ __('Two-factor authentication') }}</h3><p class="muted">{{ __('An extra layer of protection with an authenticator app.') }}</p></div><span class="account-status">{{ $user->two_factor_confirmed_at ? __('Enabled') : __('Not enabled') }}</span></div>
                @if(! $user->two_factor_secret)
                    <form method="post" action="{{ route('settings.two-factor.enable') }}">@csrf<button class="btn btn-outline" type="submit">{{ __('Set up two-factor authentication') }}</button></form>
                @elseif(time() - session('auth.password_confirmed_at', 0) > config('auth.password_timeout', 10800))
                    <a href="{{ route('password.confirm') }}" class="btn btn-outline">{{ __('Confirm password to manage security') }}</a>
                @else
                    @if(! $user->two_factor_confirmed_at)<div class="two-factor-setup"><div class="two-factor-qr">{!! $user->twoFactorQrCodeSvg() !!}</div><div><h3>{{ __('Connect your authenticator') }}</h3><p class="muted">{{ __('Scan this QR code, then enter the code shown in your app to finish setup.') }}</p><form method="post" action="{{ route('settings.two-factor.confirm') }}" class="stack">@csrf<label class="field">{{ __('Six-digit code') }}<input class="form-input" name="code" inputmode="numeric" pattern="[0-9]{6}" autocomplete="one-time-code" required></label><button class="btn btn-primary" type="submit">{{ __('Confirm setup') }}</button></form></div></div>@else
                        <details class="settings-disclosure"><summary>{{ __('Show your recovery codes') }}</summary><p class="muted">{{ __('Keep these codes somewhere private. Each code can be used once if you lose your authenticator.') }}</p><div class="recovery-codes">@foreach($user->recoveryCodes() as $code)<code>{{ $code }}</code>@endforeach</div><form method="post" action="{{ route('settings.recovery-codes') }}">@csrf<button class="btn btn-outline" type="submit">{{ __('Generate new recovery codes') }}</button></form></details>
                    @endif
                    <form method="post" action="{{ route('settings.two-factor.disable') }}">@csrf @method('DELETE')<button class="text-button" type="submit">{{ $user->two_factor_confirmed_at ? __('Disable two-factor authentication') : __('Cancel setup') }}</button></form>
                @endif
            </section>
            <section id="api" class="settings-section"><h2>{{ __('Your words, connected.') }}</h2><p class="muted">{{ __('Create a read-only token for the Folkscript API. Tokens expire after 90 days.') }}</p>
                @if(session('token'))<div class="notice"><strong>{{ __('Copy your token now') }}</strong><code class="token-value">{{ session('token') }}</code></div>@endif
                @forelse($tokens as $token)<div class="security-row"><div><h3>{{ $token->name }}</h3><p class="muted">{{ __('Created :date', ['date' => $token->created_at->format('M j, Y')]) }} · {{ $token->last_used_at ? __('Last used :time', ['time' => $token->last_used_at->diffForHumans()]) : __('Not used yet') }}</p></div><form method="post" action="{{ route('settings.tokens.revoke', $token) }}">@csrf @method('DELETE')<button class="text-button" type="submit">{{ __('Revoke') }}</button></form></div>@empty<p class="muted">{{ __('You haven’t created any API tokens.') }}</p>@endforelse
                <form method="post" action="{{ route('settings.tokens.create') }}" class="inline-form">@csrf<label class="field">{{ __('Token name') }}<input class="form-input" name="token_name" maxlength="60" placeholder="{{ __('My reading app') }}" required></label><button class="btn btn-outline" type="submit">{{ __('Create token') }}</button></form>
            </section>
            <section class="settings-section"><details class="settings-disclosure danger-disclosure"><summary>{{ __('Delete your account') }}</summary><p class="muted">{{ __('This permanently deletes your account and your stories. This action cannot be undone.') }}</p><form method="post" action="{{ route('settings.destroy') }}" class="stack">@csrf @method('DELETE')<label class="field">{{ __('Confirm your password') }}<input class="form-input" type="password" name="password" autocomplete="current-password" required></label><label class="field">{{ __('Type DELETE to confirm') }}<input class="form-input" name="confirmation" pattern="DELETE" required></label><button class="btn btn-outline" type="submit">{{ __('Permanently delete account') }}</button></form></details></section>
        </div>
    </div>
</div>
</x-layout>
