<x-layout title="{{ __('Your story collections') }}">
<div class="page-shell account-page">
    <div class="page-heading"><div><h1>{{ __('Your collections') }}</h1><p class="muted">{{ __('Build a series, explore a theme, or give your readers a place to begin.') }}</p></div><a href="/dashboard" class="btn btn-outline">{{ __('Back to your studio') }}</a></div>
    <nav class="tab-nav" aria-label="{{ __('Writing studio') }}"><a href="/dashboard">{{ __('Your stories') }}</a><a href="{{ route('series.index') }}" class="active" aria-current="page">{{ __('Collections') }} <span class="count">{{ $collections->count() }}</span></a></nav>
    <div class="settings-layout series-manager">
        <aside><nav class="settings-nav series-side-list" aria-label="{{ __('Your collections') }}">@forelse($collections as $collection)<a href="{{ route('series.edit', $collection) }}" @class(['active' => $selected?->id === $collection->id]) @if($selected?->id === $collection->id) aria-current="page" @endif><strong>{{ $collection->title }}</strong><span class="muted">{{ trans_choice('ui.story_count', $collection->posts_count) }}</span></a>@empty<p class="muted">{{ __('Your first collection begins here.') }}</p>@endforelse</nav><details class="settings-disclosure" @if(! $selected || old('collection_action') === 'create') open @endif><summary>{{ __('Create a collection') }}</summary><form method="post" action="{{ route('series.store') }}" class="stack" data-error-bag="collectionCreate">@csrf<input type="hidden" name="collection_action" value="create"><label class="field">{{ __('Collection title') }}<input aria-invalid="{{ $errors->getBag('collectionCreate')->has('title') ? 'true' : 'false' }}" aria-describedby="index1-error" class="form-input" name="title" value="{{ old('collection_action') === 'create' ? old('title') : '' }}" maxlength="100" placeholder="{{ __('A name for this chapter') }}" required><x-field-error name="title" bag="collectionCreate" id="index1-error" /></label><label class="field">{{ __('A short introduction') }}<textarea aria-invalid="{{ $errors->getBag('collectionCreate')->has('description') ? 'true' : 'false' }}" aria-describedby="index2-error" class="form-input" name="description" rows="3" maxlength="1000" placeholder="{{ __('What connects these stories?') }}">{{ old('collection_action') === 'create' ? old('description') : '' }}</textarea><x-field-error name="description" bag="collectionCreate" id="index2-error" /></label><button class="btn btn-primary" type="submit">{{ __('Create collection') }}</button></form></details></aside>
        <div class="settings-content">
            @if($selected)
                <section class="settings-section"><div class="section-heading"><div><h2>{{ $selected->title }}</h2><p class="muted">{{ __('By :name', ['name' => $selected->author->name]) }}</p></div><a class="btn btn-outline" href="{{ route('series.show', ['username' => $selected->author->username, 'slug' => $selected->slug]) }}">{{ __('View collection ↗') }}</a></div>
                    <form method="post" action="{{ route('series.update', $selected) }}" class="stack" data-error-bag="collectionUpdate">@csrf @method('PATCH')<input type="hidden" name="collection_action" value="edit"><label class="field">{{ __('Title') }}<input aria-invalid="{{ $errors->getBag('collectionUpdate')->has('title') ? 'true' : 'false' }}" aria-describedby="index3-error" class="form-input" name="title" value="{{ old('collection_action') === 'edit' ? old('title', $selected->title) : $selected->title }}" maxlength="100" required><x-field-error name="title" bag="collectionUpdate" id="index3-error" /></label><label class="field">{{ __('Introduction') }}<textarea aria-invalid="{{ $errors->getBag('collectionUpdate')->has('description') ? 'true' : 'false' }}" aria-describedby="index4-error" class="form-input" name="description" rows="3" maxlength="1000">{{ old('collection_action') === 'edit' ? old('description', $selected->description) : $selected->description }}</textarea><x-field-error name="description" bag="collectionUpdate" id="index4-error" /></label><button class="btn btn-outline" type="submit">{{ __('Save details') }}</button></form>
                </section>
                <section class="settings-section"><h2>{{ __('Reading order') }}</h2><x-field-error name="positions" /><p class="muted">{{ __('Set each story’s position, then save the order. Drafts and scheduled stories stay private until they are published.') }}</p>
                    @if($selected->posts->count())<form id="series-order" method="post" action="{{ route('series.order', $selected) }}">@csrf @method('PATCH')</form><div class="series-story-list">@foreach($selected->posts as $post)<div class="series-story-row"><label class="field"><span class="sr-only">{{ __('Position for :title', ['title' => $post->title]) }}</span><input form="series-order" type="number" name="positions[{{ $post->id }}]" min="1" max="1000" value="{{ $loop->iteration }}" class="form-input" required></label><div><a href="/write/{{ $post->id }}">{{ $post->title }}</a><span class="muted">{{ __('ui.status.'.$post->status) }} · {{ trans_choice('ui.reading_minutes', $post->reading_time) }}</span></div><form method="post" action="{{ route('series.posts.detach', ['series' => $selected, 'post' => $post]) }}">@csrf @method('DELETE')<button type="submit" class="text-button" aria-label="{{ __('Remove :title from collection', ['title' => $post->title]) }}">{{ __('Remove') }}</button></form></div>@endforeach</div><button form="series-order" class="btn btn-primary" type="submit">{{ __('Save reading order') }}</button>@else<div class="series-empty"><p>{{ __('No stories here yet. Add your first one below.') }}</p></div>@endif
                    @if($available->count())<form method="post" action="{{ route('series.posts.attach', $selected) }}" class="inline-form">@csrf<label class="field">{{ __('Add a story') }}<select aria-invalid="{{ $errors->getBag('default')->has('post_id') ? 'true' : 'false' }}" aria-describedby="index5-error" class="form-input" name="post_id" required><option value="">{{ __('Choose one of your stories') }}</option>@foreach($available as $post)<option value="{{ $post->id }}">{{ $post->title }} ({{ __('ui.status.'.$post->status) }})</option>@endforeach</select><x-field-error name="post_id" bag="default" id="index5-error" /></label><button class="btn btn-outline" type="submit">{{ __('Add story') }}</button></form>@else<p class="muted series-empty">{{ $selected->posts->count() ? __('All your available stories are in this collection.') : __('Write your first story, then add it to this collection.') }} <a href="/write">{{ __('Start a story →') }}</a></p>@endif
                </section>
                <details class="settings-disclosure"><summary>{{ __('Delete this collection') }}</summary><p class="muted">{{ __('The collection will be removed. Your stories will stay in your writing studio.') }}</p><form method="post" action="{{ route('series.destroy', $selected) }}">@csrf @method('DELETE')<button class="btn btn-outline" type="submit">{{ __('Delete collection') }}</button></form></details>
            @else<div class="series-welcome"><x-icon name="book-open" size="36" /><h2>{{ __('Give your stories a shared home.') }}</h2><p>{{ __('Create a collection, add your stories, and arrange them in the order you want readers to discover them.') }}</p></div>@endif
        </div>
    </div>
</div>
</x-layout>
