<section id="stories" class="admin-section" aria-labelledby="stories-heading">
    <h2 id="stories-heading" class="sr-only">{{ __('Stories') }}</h2>
    <nav class="admin-filter-tabs" aria-label="{{ __('Filter stories by status') }}">@foreach(['published' => __('Published'), 'draft' => __('Drafts'), 'scheduled' => __('Scheduled'), 'archived' => __('Archived')] as $value => $label)<a href="{{ route('admin', ['view' => 'stories', 'story_status' => $value, 'story_q' => $storyQuery]) }}" @if($storyStatus === $value) aria-current="page" @endif>{{ $label }} @if($storyStatus === $value)<span>{{ $posts->total() }}</span>@endif</a>@endforeach</nav>
    <form method="get" action="{{ route('admin') }}" class="admin-list-toolbar"><input type="hidden" name="view" value="stories"><input type="hidden" name="story_status" value="{{ $storyStatus }}"><div class="admin-search-field"><x-icon name="search" size="18" /><label class="sr-only" for="story-search">{{ __('Search stories by title or writer') }}</label><input class="form-input" id="story-search" type="search" name="story_q" value="{{ $storyQuery }}" placeholder="{{ __('Search by title or writer…') }}" maxlength="200"></div><button class="btn btn-outline">{{ __('Search') }}</button>@if($storyQuery !== '')<a class="admin-row-action" href="{{ route('admin', ['view' => 'stories', 'story_status' => $storyStatus]) }}">{{ __('Clear search') }}</a>@endif</form>
        <div class="admin-table-wrap"><table class="admin-table admin-responsive-table admin-stories-table"><caption class="sr-only">{{ __('Stories and publishing actions') }}</caption><thead><tr><th scope="col">{{ __('Story') }}</th><th scope="col">{{ __('Writer') }}</th><th scope="col">{{ $storyStatus === 'published' ? __('Published') : __('Updated') }}</th><th scope="col">{{ __('Actions') }}</th></tr></thead><tbody>
            @forelse($posts as $post)
                <tr><td class="admin-story-cell"><a class="admin-story-title" href="{{ $post->status === 'published' ? $post->url : url('/write/'.$post->id) }}">{{ $post->title }}</a></td><td class="admin-writer-cell"><span class="admin-cell-label">{{ __('By') }}</span> <a class="admin-writer-identity" href="{{ '/@'.$post->author->username }}"><x-avatar :user="$post->author" size="tiny" /><span>{{ $post->author->name }}</span></a></td><td class="admin-date-cell"><time datetime="{{ ($post->status === 'published' ? $post->published_at : $post->updated_at)?->toIso8601String() }}">{{ ($post->status === 'published' ? $post->published_at : $post->updated_at)?->format('M j, Y') }}</time></td><td class="admin-story-actions"><div class="admin-story-controls"><a class="text-button" href="{{ url('/write/'.$post->id) }}" aria-label="{{ __('Edit :title', ['title' => $post->title]) }}">{{ __('Edit story') }}</a>@if($post->status === 'published')<details class="admin-confirm"><summary>{{ __('Unpublish') }}</summary><p>{{ __('Readers will no longer see this story. Its author can revise and republish it.') }}</p><form method="post" action="{{ route('admin.posts.update', array_merge([$post], $returnQuery)) }}">@csrf @method('PATCH')<button class="btn btn-outline" type="submit" aria-label="{{ __('Unpublish :title', ['title' => $post->title]) }}">{{ __('Unpublish story') }}</button></form></details>@endif</div></td></tr>
            @empty<tr><td colspan="4"><div class="admin-empty"><h3>{{ __('No stories found') }}</h3><p>{{ $storyQuery !== '' ? __('Try another title or writer, or clear your search.') : __('Stories with this status will appear here.') }}</p></div></td></tr>@endforelse
        </tbody></table></div>
        <div class="admin-pagination">{{ $posts->withQueryString()->fragment('stories')->links() }}</div>
    </section>
