<div class="editor-shell" wire:key="story-editor" x-data="storyEditor($wire)" @keydown.ctrl.s.window.prevent="saveShortcut()" @keydown.meta.s.window.prevent="saveShortcut()">
    <header class="editor-topbar">
        <div class="editor-heading"><a href="{{ route('dashboard') }}" class="icon-button" aria-label="{{ __('Back to studio') }}"><x-icon name="arrow-left" /></a><h1>{{ __('Story editor') }}</h1></div>
        <div class="editor-save-actions">
            <button type="button" class="btn btn-outline" @click="askForDraft()" :disabled="busy || uploading || !ready">{{ $status === 'draft' ? __('Save draft') : __('Move to drafts') }}</button>
            <button type="button" class="btn btn-primary" @click="submit('publish')" :disabled="busy || uploading || !ready"><span x-text="pendingAction === 'publish' ? @js(__('Publishing…')) : ($wire.status === 'published' ? @js(__('Update story')) : @js(__('Publish now')))"></span><x-icon name="arrow-up-right" size="16" /></button>
        </div>
        <p class="editor-save-status" :class="{ 'has-error': saveError }" role="status" aria-live="polite" x-text="statusText"></p>
    </header>

    <div class="editor-feedback notice notice-error" x-show="saveError" x-cloak role="alert"><p x-text="saveError"></p><button type="button" class="text-link" x-show="ready && $wire.status === 'draft'" @click="submit('saveDraft')" :disabled="busy || !online">{{ __('Try saving again') }}</button><button type="button" class="text-link" x-show="ready" @click="exportMarkdown()">{{ __('Download a Markdown copy') }}</button></div>
    @if($errors->any())
        <div class="notice notice-error editor-validation" role="alert" tabindex="-1" x-ref="validationErrors"><strong>{{ __('Please check these details before saving.') }}</strong><ul>@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>
    @endif
    <section class="editor-confirmation" x-show="confirmation" x-cloak x-ref="confirmationPanel" tabindex="-1" @keydown.escape.prevent="closeConfirmation()" aria-label="{{ __('Confirm story change') }}">
        <h2 x-text="confirmation?.title"></h2><p x-text="confirmation?.message"></p><div class="form-actions"><button type="button" class="btn btn-primary" @click="submit(confirmation.action, confirmation.id)" :disabled="busy"><span x-text="confirmation?.label"></span></button><button type="button" class="btn btn-outline" @click="closeConfirmation()" :disabled="busy">{{ __('Keep editing') }}</button></div>
    </section>

    <div class="editor-grid" :inert="busy && pendingAction !== 'autosave'">
        <div class="editor-main">
            <div class="editor-cover">
                <template x-if="$wire.coverImage"><img :src="$wire.coverImage" alt="{{ __('Story cover preview') }}"></template>
                <input type="file" accept="image/jpeg,image/png,image/webp,image/avif" x-ref="coverInput" @change="uploadCover($event)" class="sr-only" id="cover-upload" tabindex="-1">
                <div class="editor-cover-actions"><button class="text-link" type="button" @click="$refs.coverInput.click()" :disabled="uploading || !ready"><x-icon name="image-plus" size="19" /><span x-text="uploading ? @js(__('Uploading image…')) : ($wire.coverImage ? @js(__('Change cover')) : @js(__('Add a cover image')))"></span></button><button type="button" class="text-link" x-show="$wire.coverImage" @click="removeCover()" :disabled="uploading">{{ __('Remove cover') }}</button></div>
                <p class="editor-help">{{ __('Optional. JPG, PNG, WebP or AVIF, up to 5 MB.') }}</p>
                @error('coverImage')<p class="field-error">{{ $message }}</p>@enderror
            </div>
            <p x-show="uploadError" x-text="uploadError" x-cloak class="field-error editor-upload-error" role="alert"></p>
            <label class="sr-only" for="story-title">{{ __('Story title') }}</label>
            <textarea id="story-title" class="editor-title" wire:model="title" @input="markChanged()" placeholder="{{ __('Give your story a title…') }}" rows="2" maxlength="200" aria-describedby="title-error" @error('title') aria-invalid="true" @enderror></textarea>
            @error('title')<p id="title-error" class="field-error">{{ $message }}</p>@enderror
            <label class="sr-only" for="story-excerpt">{{ __('Story summary') }}</label>
            <textarea id="story-excerpt" class="editor-excerpt" wire:model="excerpt" @input="markChanged()" placeholder="{{ __('Add a short summary (optional)') }}" rows="2" maxlength="500" aria-describedby="excerpt-error" @error('excerpt') aria-invalid="true" @enderror></textarea>
            @error('excerpt')<p id="excerpt-error" class="field-error">{{ $message }}</p>@enderror
            <div wire:ignore>
                <div class="editor-toolbar" role="group" aria-label="{{ __('Format your story') }}">
                    @foreach(['bold'=>['bold','Bold'],'italic'=>['italic','Italic'],'strike'=>['strikethrough','Strikethrough'],'h2'=>['heading-2','Heading 2'],'h3'=>['heading-3','Heading 3'],'quote'=>['quote','Block quote'],'bullet'=>['list','Bullet list'],'ordered'=>['list-ordered','Numbered list'],'code'=>['code','Code block']] as $command => [$icon, $label])
                        <button type="button" @click="format(@js($command))" :aria-pressed="!!active.{{ $command }}" :class="{ active: active.{{ $command }} }" :disabled="!ready" title="{{ __($label) }}" aria-label="{{ __($label) }}"><x-icon :name="$icon" size="18" /></button>
                    @endforeach
                    <span class="toolbar-divider" aria-hidden="true"></span>
                    <button type="button" @click="openTool('link')" :aria-pressed="!!active.link" :class="{ active: active.link }" :disabled="!ready" title="{{ __('Add or edit link') }}" aria-label="{{ __('Add or edit link') }}"><x-icon name="link" size="18" /></button>
                    <button type="button" @click="$refs.bodyImage.click()" :disabled="!ready || uploading" title="{{ __('Insert image') }}" aria-label="{{ __('Insert image') }}"><x-icon name="image" size="18" /></button>
                    <button type="button" @click="openTool('video')" :disabled="!ready" title="{{ __('Embed YouTube video') }}" aria-label="{{ __('Embed YouTube video') }}"><x-icon name="video" size="18" /></button>
                    <button type="button" @click="format('rule')" :disabled="!ready" title="{{ __('Insert divider') }}" aria-label="{{ __('Insert divider') }}"><x-icon name="minus" size="18" /></button>
                    <span class="toolbar-divider" aria-hidden="true"></span>
                    <button type="button" @click="format('undo')" :disabled="!ready || !canUndo" title="{{ __('Undo') }}" aria-label="{{ __('Undo') }}"><x-icon name="undo-2" size="18" /></button>
                    <button type="button" @click="format('redo')" :disabled="!ready || !canRedo" title="{{ __('Redo') }}" aria-label="{{ __('Redo') }}"><x-icon name="redo-2" size="18" /></button>
                </div>
                <input type="file" accept="image/jpeg,image/png,image/webp,image/avif" x-ref="bodyImage" @change="selectBodyImage($event)" class="sr-only" tabindex="-1" aria-label="{{ __('Upload story image') }}">
                <input type="file" accept=".md,.markdown,text/markdown,text/plain" x-ref="markdownFile" @change="importMarkdown($event)" class="sr-only" tabindex="-1" aria-label="{{ __('Import Markdown file') }}">
                <section class="editor-tool-panel" x-show="tool" x-cloak @keydown.escape.prevent.stop="closeTool()" aria-label="{{ __('Insert content') }}">
                    <div x-show="tool === 'link' || tool === 'video'">
                        <label for="editor-tool-url" x-text="tool === 'link' ? @js(__('Link address')) : @js(__('YouTube video link'))"></label>
                        <input id="editor-tool-url" class="form-input" type="text" inputmode="url" x-model="toolValue" x-ref="toolUrl" placeholder="https://…" @keydown.enter.prevent="applyTool()" aria-describedby="editor-tool-help editor-tool-error">
                        <p class="editor-help" id="editor-tool-help" x-text="tool === 'link' ? @js(__('Select text first, or we’ll use the address as the link text. Clear the address to remove an existing link.')) : @js(__('Use a youtube.com/watch or youtu.be link.'))"></p>
                    </div>
                    <div x-show="tool === 'image'">
                        <label for="image-description">{{ __('Describe this image') }}</label><input id="image-description" class="form-input" type="text" x-model="imageAlt" x-ref="imageDescription" maxlength="300" placeholder="{{ __('What should a reader know about this image?') }}" @keydown.enter.prevent="uploadImage(imageFile, 'body')" aria-describedby="image-alt-help">
                        <p id="image-alt-help" class="editor-help">{{ __('This description is read aloud by screen readers. Leave it empty only if the image is decorative.') }}</p>
                    </div>
                    <div x-show="tool === 'markdown'"><h3>{{ __('Replace the story text?') }}</h3><p>{{ __('Importing Markdown replaces the text below. Your title and publishing settings stay as they are. You can undo the import in the editor.') }}</p></div>
                    <p id="editor-tool-error" class="field-error" x-show="toolError" x-text="toolError" role="alert"></p>
                    <div class="form-actions"><button type="button" class="btn btn-primary" @click="tool === 'image' ? uploadImage(imageFile, 'body') : applyTool()" :disabled="uploading"><span x-text="uploading ? @js(__('Uploading…')) : tool === 'image' ? @js(__('Insert image')) : tool === 'markdown' ? @js(__('Replace text')) : @js(__('Apply'))"></span></button><button type="button" class="btn btn-outline" @click="closeTool()" :disabled="uploading">{{ __('Cancel') }}</button></div>
                </section>
                <p x-show="!ready && !saveError" role="status" class="editor-help">{{ __('Loading your writing tools…') }}</p>
                <div x-ref="editor" class="prose editor-body" aria-label="{{ __('Story body') }}"></div>
                <div class="editor-writing-footer"><p class="editor-wordcount"><span x-text="wordCount"></span> {{ __('words') }} <span aria-hidden="true"> · </span><span x-text="Math.max(1, Math.ceil(wordCount / 220))"></span> {{ __('min read') }}</p><div><button type="button" class="text-link" @click="$refs.markdownFile.click()" :disabled="!ready">{{ __('Import Markdown') }}</button><button type="button" class="text-link" @click="exportMarkdown()" :disabled="!ready">{{ __('Download Markdown') }}</button></div></div>
            </div>
            @error('bodyHtml')<p class="field-error" role="alert">{{ $message }}</p>@enderror
        </div>
        <aside class="editor-sidebar">
            <section><h2>{{ __('Publish settings') }}</h2>
                @if($post?->status === 'published')<a class="text-link editor-public-link" href="{{ $post->url }}" target="_blank" rel="noopener">{{ __('View published story') }} <x-icon name="external-link" size="15" /></a>@endif
                <fieldset class="editor-topics"><legend>{{ __('Topics') }}</legend><p class="editor-help">{{ __('Choose up to 5 topics where readers can find your story.') }}</p><div>@foreach($categories as $category)<label class="checkbox"><input type="checkbox" value="{{ $category->id }}" wire:model="categoryIds" @change="markChanged()"><span>{{ $category->name }}</span></label>@endforeach</div>@error('categoryIds')<p class="field-error">{{ $message }}</p>@enderror</fieldset>
                <div class="field"><label for="story-tags">{{ __('Tags') }}</label><input id="story-tags" class="form-input" wire:model="tagNames" @input="markChanged()" placeholder="{{ __('Creativity, everyday life') }}" maxlength="250" aria-describedby="tags-help"><small id="tags-help">{{ __('Up to 5 tags, separated by commas.') }}</small>@error('tagNames')<p class="field-error">{{ $message }}</p>@enderror</div>
                <div class="field"><label for="story-slug">{{ __('Story URL') }}</label><input id="story-slug" class="form-input" wire:model="slug" @input="markChanged()" placeholder="{{ __('created-from-your-title') }}" maxlength="200" aria-describedby="slug-help" spellcheck="false"><small id="slug-help">{{ parse_url(config('app.url'), PHP_URL_HOST) }}{{ '/@'.auth()->user()->username }}/<span x-text="$wire.slug || '…'"></span></small>@error('slug')<p class="field-error">{{ $message }}</p>@enderror</div>
                <label class="checkbox editor-premium"><input type="checkbox" wire:model="isPremium" @change="markChanged()"><span>{{ __('Members only') }}<small>{{ __('Members can read the full story. Everyone else sees a preview.') }}</small></span></label>
                <details class="editor-schedule" @if($status === 'scheduled') open @endif><summary>{{ $status === 'scheduled' ? __('Publication schedule') : __('Schedule for later') }}</summary><div class="field"><label for="publish-date">{{ __('Date and time') }}</label><input id="publish-date" type="datetime-local" class="form-input" wire:model="publishedAt" @input="markChanged()" aria-describedby="schedule-help"><small id="schedule-help">{{ __('All times are in :timezone. Choose a future time.', ['timezone' => config('app.timezone')]) }}</small>@error('publishedAt')<p class="field-error">{{ $message }}</p>@enderror</div><p class="editor-help" x-show="$wire.status === 'published'">{{ __('Scheduling this story removes it from public view until the chosen time.') }}</p><button type="button" class="btn btn-outline" @click="submit('schedule')" :disabled="busy || uploading || !$wire.publishedAt || !ready"><x-icon name="calendar" size="15" /><span x-text="$wire.status === 'scheduled' ? @js(__('Update schedule')) : @js(__('Schedule story'))"></span></button></details>
                @if($revisions->isNotEmpty())<details class="editor-revisions"><summary>{{ __('Revision history') }}</summary><p class="editor-help">{{ __('Restore an earlier title and story text. Your current text will be kept as another version.') }} {{ __('Times are shown in :timezone.', ['timezone' => config('app.timezone')]) }}</p><div class="stack">@foreach($revisions as $revision)<button type="button" class="text-link" @click="askToRestore({{ $revision->id }}, @js($revision->created_at->format('M j, g:i A')))" :disabled="busy"><x-icon name="history" size="15" /><span>{{ $revision->created_at->format('M j, g:i A') }}<small>{{ Str::limit($revision->title, 38) }}</small></span></button>@endforeach</div></details>@endif
            </section>
            <section><h2>{{ __('Search preview') }}</h2><p class="section-description">{{ __('Optional details for search engines and shared links. Leave these empty to use your title and summary.') }}</p>
                <div class="field"><label for="meta-title">{{ __('Search title') }}</label><input id="meta-title" class="form-input" wire:model="metaTitle" @input="markChanged()" placeholder="{{ __('Use your story title') }}" maxlength="60" aria-describedby="meta-title-count"><span id="meta-title-count" class="character-count"><span x-text="$wire.metaTitle.length"></span> / 60 {{ __('characters') }}</span><small>{{ __('Around 50–60 characters usually fits well in search results.') }}</small>@error('metaTitle')<p class="field-error">{{ $message }}</p>@enderror</div>
                <div class="field"><label for="meta-description">{{ __('Search description') }}</label><textarea id="meta-description" class="form-input" wire:model="metaDescription" @input="markChanged()" placeholder="{{ __('Use your story summary') }}" rows="4" maxlength="160" aria-describedby="meta-description-count"></textarea><span id="meta-description-count" class="character-count"><span x-text="$wire.metaDescription.length"></span> / 160 {{ __('characters') }}</span><small>{{ __('Aim for a clear summary, up to 150–160 characters.') }}</small>@error('metaDescription')<p class="field-error">{{ $message }}</p>@enderror</div>
                <div class="og-preview"><template x-if="$wire.coverImage"><img :src="$wire.coverImage" alt="" width="280" height="147"></template><div><span>{{ parse_url(config('app.url'), PHP_URL_HOST) }}</span><strong x-text="$wire.metaTitle || $wire.title || @js(__('Your story title'))"></strong><p x-text="$wire.metaDescription || $wire.excerpt || @js(__('Your story summary will appear here.'))"></p></div></div>
                <details class="editor-guidance"><summary>{{ __('Writing guidance') }}</summary><p class="editor-help">{{ __('Suggestions to consider, never a checklist you need to pass.') }}</p><ul><li><strong>{{ __('Image descriptions') }}</strong><p x-text="imageCount === 0 ? @js(__('No story images yet, so there are no descriptions to check.')) : describedImages === imageCount ? @js(__('Every story image has a description. Check that each one adds useful context.')) : @js(__('Some images have no description. Add alt text to images that carry meaning; decorative images can stay empty.'))"></p></li><li><strong>{{ __('Related reading') }}</strong><p x-text="hasInternalLink ? @js(__('You’ve linked to another Folkscript story. Make the link text explain what readers will find.')) : @js(__('When another Folkscript story adds context, consider linking to it. A link is useful only when it helps your reader.'))"></p></li><li><strong>{{ __('Your opening') }}</strong><p>{{ __('Give readers a clear way into your idea. A specific observation or first-hand experience is often more useful than a broad claim.') }}</p></li></ul></details>
                <details class="editor-canonical"><summary>{{ __('Already published elsewhere?') }}</summary><div class="field"><label for="canonical-url">{{ __('Original story URL') }}</label><input id="canonical-url" type="url" wire:model="canonicalUrl" @input="markChanged()" class="form-input" placeholder="https://your-site.com/story" maxlength="2048" aria-describedby="canonical-help"><small id="canonical-help">{{ __('Leave empty if Folkscript is the original home. This tells search engines which version came first.') }}</small>@error('canonicalUrl')<p class="field-error">{{ $message }}</p>@enderror</div></details>
            </section>
        </aside>
    </div>
</div>
